FROM jenkins/jenkins:lts
USER root

# Install Python and related tools
#RUN apt-get update \
#    && apt-get install -y python3 python3-pip \
#    && pip3 install --upgrade pip

RUN apt-get update
RUN apt-get install python
RUN apt-get install libpq-dev
RUN apt-get install python-pip

# Install any additional Python packages you need for your Jenkins setup
# For example, if you want to install the 'requests' package, uncomment the following line
# RUN pip3 install requests



RUN pip install psycopg2
RUN pip install requests
RUN pip install airflow

USER jenkins